#!/bin/bash

set -e

./gradlew check bootJar

echo "${DC_PAT}" | docker login -u albertattard --password-stdin
docker buildx use multi-platform-builder
docker build \
  --file=./container/Dockerfile \
  --platform linux/amd64,linux/arm64 \
  --tag albertattard/gourami-app:latest \
  --push \
  .
