auth0:
  audience: ${AUTH0_AUDIENCE}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      base-path: /public/actuator

logging:
  level:
    root: INFO
    gourami: DEBUG
